name: music
channels:
  - defaults
dependencies:
  - ca-certificates
  - openssl
  - pip
  - python
  - setuptools
  - sqlite
  - wheel
  - pip:
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - async-timeout
      - attrs
      - audioop-lts
      - audioread
      - cffi
      - charset-normalizer
      - colorama
      - contourpy
      - decorator
      - datasets
      - dill
      - filelock
      - fonttools
      - frozenlist
      - fsspec
      - huggingface-hub
      - idna
      - importlib-resources
      - jinja2
      - joblib
      - kiwisolver
      - lazy_loader
      - librosa
      - llvmlite
      - markupsafe
      - matplotlib
      - mpmath
      - msgpack
      - multiprocess
      - networkx
      - numpy
      - packaging
      - pandas
      - pillow
      - platformdirs
      - pooch
      - propcache
      - pyarrow
      - pyparsing
      - python-dateutil
      - python-osc
      - python-sonic
      - pytokens
      - pytz
      - pyyaml
      - regex
      - requests
      - safetensors
      - scikit-learn
      - scipy
      - seaborn
      - sentence-transformers
      - six
      - soundfile
      - soxr
      - sympy
      - threadpoolctl
      - tokenizers
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - transformers
      - typing-extensions
      - tzdata
      - urllib3
      - xxhash
      - yarl
      - zipp